package interfaz;

import entidades.Cliente;
import entidades.Compra;
import entidades.Pelicula;
import gestor.ArchivoCliente;
import gestor.ArchivoCompras;
import gestor.ArchivoPelicula;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.lang.constant.DirectMethodHandleDesc;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Dtapiaj
 */
public class GestionPeliculas extends javax.swing.JFrame {

    String rutaArchivoPelicula = new File("").getAbsolutePath() + "\\src\\archivos\\peliculas.txt";
    ArchivoPelicula archivoPelicula = new ArchivoPelicula(rutaArchivoPelicula);

    String rutaArchivoCliente = new File("").getAbsolutePath() + "\\src\\archivos\\clientes.txt";
    ArchivoCliente archivoCliente = new ArchivoCliente(rutaArchivoCliente);
    
    String rutaArchivoCompra = new File("").getAbsolutePath() + "\\src\\archivos\\compras.txt";
    ArchivoCompras archivoCompra = new ArchivoCompras(rutaArchivoCompra, rutaArchivoCliente, rutaArchivoPelicula);
    
    ArrayList<Compra> compras;
    ArrayList<Pelicula> peliculas;
    ArrayList<Compra> comprasCliente;
    
    private String idAdministrador = "admin";
    /**
     * Creates new form GestionPeliculas
     */
    public GestionPeliculas() {
        initComponents();
        compras = archivoCompra.leerCompra();
        peliculas = archivoPelicula.leerPeliculas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteRegistrado = new javax.swing.JFrame();
        clienteNoRegistrado = new javax.swing.JFrame();
        adminFrame = new javax.swing.JFrame();
        panelID = new javax.swing.JPanel();
        txtIdPelicula = new javax.swing.JTextField();
        panelTitulo = new javax.swing.JPanel();
        txtTituloPelicula = new javax.swing.JTextField();
        panelDirector = new javax.swing.JPanel();
        txtDirectorPelicula = new javax.swing.JTextField();
        panelCompras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsultarCompras = new javax.swing.JTextArea();
        btnTodasCompras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdClienteConsultar = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPeliculasAdmin = new javax.swing.JTextArea();
        tituloRegistrarPelicula1 = new javax.swing.JLabel();
        tituloRegistrarPelicula = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegistrarPelicula = new javax.swing.JButton();
        btnModificarPelicula = new javax.swing.JButton();
        btnEliminarPelicula = new javax.swing.JButton();
        txtPrecioPelicula = new javax.swing.JTextField();
        txtAñoPelicula = new javax.swing.JTextField();
        txtGeneroPelicula = new javax.swing.JTextField();
        btnMostrarPeliculas = new javax.swing.JButton();
        descrAdmin = new javax.swing.JLabel();
        btnRegresarAdmin_main = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        panelAño = new javax.swing.JPanel();
        txtDirectorPelicula1 = new javax.swing.JTextField();
        modificarFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        panelCompras1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsultarCompras1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtIdClienteConsultar1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarCliente1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresarModificar_Admin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        autores = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        iconPelicenter = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAcceder = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtIdSesion = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        clienteRegistrado.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        clienteRegistrado.setResizable(false);
        clienteRegistrado.setSize(new java.awt.Dimension(880, 500));

        javax.swing.GroupLayout clienteRegistradoLayout = new javax.swing.GroupLayout(clienteRegistrado.getContentPane());
        clienteRegistrado.getContentPane().setLayout(clienteRegistradoLayout);
        clienteRegistradoLayout.setHorizontalGroup(
            clienteRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        clienteRegistradoLayout.setVerticalGroup(
            clienteRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        clienteNoRegistrado.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        clienteNoRegistrado.setResizable(false);
        clienteNoRegistrado.setSize(new java.awt.Dimension(880, 500));

        javax.swing.GroupLayout clienteNoRegistradoLayout = new javax.swing.GroupLayout(clienteNoRegistrado.getContentPane());
        clienteNoRegistrado.getContentPane().setLayout(clienteNoRegistradoLayout);
        clienteNoRegistradoLayout.setHorizontalGroup(
            clienteNoRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        clienteNoRegistradoLayout.setVerticalGroup(
            clienteNoRegistradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        adminFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        adminFrame.setPreferredSize(new java.awt.Dimension(890, 535));
        adminFrame.setResizable(false);
        adminFrame.setSize(new java.awt.Dimension(890, 535));
        adminFrame.getContentPane().setLayout(null);

        panelID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        panelID.setOpaque(false);
        panelID.setLayout(null);

        txtIdPelicula.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPelicula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdPelicula.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPelicula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdPelicula.setBorder(null);
        txtIdPelicula.setCaretColor(new java.awt.Color(0, 0, 0));
        panelID.add(txtIdPelicula);
        txtIdPelicula.setBounds(10, 5, 340, 20);

        adminFrame.getContentPane().add(panelID);
        panelID.setBounds(100, 50, 360, 30);

        panelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        panelTitulo.setOpaque(false);
        panelTitulo.setLayout(null);

        txtTituloPelicula.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloPelicula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTituloPelicula.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloPelicula.setBorder(null);
        txtTituloPelicula.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTituloPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloPeliculaActionPerformed(evt);
            }
        });
        panelTitulo.add(txtTituloPelicula);
        txtTituloPelicula.setBounds(10, 5, 340, 20);

        adminFrame.getContentPane().add(panelTitulo);
        panelTitulo.setBounds(100, 90, 360, 30);

        panelDirector.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        panelDirector.setOpaque(false);
        panelDirector.setLayout(null);

        txtDirectorPelicula.setBackground(new java.awt.Color(255, 255, 255));
        txtDirectorPelicula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDirectorPelicula.setForeground(new java.awt.Color(0, 0, 0));
        txtDirectorPelicula.setBorder(null);
        txtDirectorPelicula.setCaretColor(new java.awt.Color(0, 0, 0));
        panelDirector.add(txtDirectorPelicula);
        txtDirectorPelicula.setBounds(10, 5, 340, 20);

        adminFrame.getContentPane().add(panelDirector);
        panelDirector.setBounds(100, 130, 360, 30);

        panelCompras.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras.setForeground(new java.awt.Color(51, 51, 51));
        panelCompras.setLayout(null);

        txtConsultarCompras.setBackground(new java.awt.Color(51, 51, 51));
        txtConsultarCompras.setColumns(20);
        txtConsultarCompras.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtConsultarCompras.setForeground(new java.awt.Color(255, 255, 255));
        txtConsultarCompras.setRows(5);
        jScrollPane2.setViewportView(txtConsultarCompras);

        panelCompras.add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 320, 280);

        btnTodasCompras.setBackground(new java.awt.Color(204, 255, 204));
        btnTodasCompras.setForeground(new java.awt.Color(0, 0, 0));
        btnTodasCompras.setText("Todas las compras");
        btnTodasCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTodasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodasComprasActionPerformed(evt);
            }
        });
        panelCompras.add(btnTodasCompras);
        btnTodasCompras.setBounds(180, 70, 140, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID cliente");
        panelCompras.add(jLabel1);
        jLabel1.setBounds(20, 21, 80, 30);

        txtIdClienteConsultar.setBackground(new java.awt.Color(51, 51, 51));
        txtIdClienteConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdClienteConsultar.setForeground(new java.awt.Color(255, 255, 255));
        panelCompras.add(txtIdClienteConsultar);
        txtIdClienteConsultar.setBounds(100, 20, 220, 30);

        btnBuscarCliente.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        panelCompras.add(btnBuscarCliente);
        btnBuscarCliente.setBounds(30, 70, 110, 30);

        adminFrame.getContentPane().add(panelCompras);
        panelCompras.setBounds(510, 40, 340, 400);

        txtPeliculasAdmin.setBackground(new java.awt.Color(51, 51, 51));
        txtPeliculasAdmin.setColumns(20);
        txtPeliculasAdmin.setForeground(new java.awt.Color(255, 255, 255));
        txtPeliculasAdmin.setLineWrap(true);
        txtPeliculasAdmin.setRows(5);
        jScrollPane1.setViewportView(txtPeliculasAdmin);

        adminFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 310, 430, 130);

        tituloRegistrarPelicula1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tituloRegistrarPelicula1.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegistrarPelicula1.setText("Consultar Compras");
        adminFrame.getContentPane().add(tituloRegistrarPelicula1);
        tituloRegistrarPelicula1.setBounds(620, 10, 150, 30);

        tituloRegistrarPelicula.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tituloRegistrarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        tituloRegistrarPelicula.setText("Registrar Pelicula");
        adminFrame.getContentPane().add(tituloRegistrarPelicula);
        tituloRegistrarPelicula.setBounds(180, 10, 140, 30);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        adminFrame.getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 50, 30, 30);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Titulo");
        adminFrame.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 90, 60, 30);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Director");
        adminFrame.getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 130, 80, 30);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Año");
        adminFrame.getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 170, 80, 21);

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Genero");
        adminFrame.getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 200, 80, 21);

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio");
        adminFrame.getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 230, 80, 21);

        btnRegistrarPelicula.setBackground(new java.awt.Color(153, 255, 0));
        btnRegistrarPelicula.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarPelicula.setText("Registrar");
        btnRegistrarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPeliculaActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(btnRegistrarPelicula);
        btnRegistrarPelicula.setBounds(50, 270, 80, 30);

        btnModificarPelicula.setBackground(new java.awt.Color(0, 102, 153));
        btnModificarPelicula.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarPelicula.setText("Modificar");
        btnModificarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPeliculaActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(btnModificarPelicula);
        btnModificarPelicula.setBounds(150, 270, 90, 30);

        btnEliminarPelicula.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarPelicula.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarPelicula.setText("Eliminar");
        btnEliminarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliculaActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(btnEliminarPelicula);
        btnEliminarPelicula.setBounds(360, 270, 90, 30);

        txtPrecioPelicula.setBackground(new java.awt.Color(51, 51, 51));
        txtPrecioPelicula.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtPrecioPelicula.setForeground(new java.awt.Color(255, 255, 255));
        adminFrame.getContentPane().add(txtPrecioPelicula);
        txtPrecioPelicula.setBounds(110, 230, 340, 20);

        txtAñoPelicula.setBackground(new java.awt.Color(51, 51, 51));
        txtAñoPelicula.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtAñoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        adminFrame.getContentPane().add(txtAñoPelicula);
        txtAñoPelicula.setBounds(110, 170, 340, 20);

        txtGeneroPelicula.setBackground(new java.awt.Color(51, 51, 51));
        txtGeneroPelicula.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtGeneroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        adminFrame.getContentPane().add(txtGeneroPelicula);
        txtGeneroPelicula.setBounds(110, 200, 340, 20);

        btnMostrarPeliculas.setBackground(new java.awt.Color(153, 255, 0));
        btnMostrarPeliculas.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarPeliculas.setText("Mostrar");
        btnMostrarPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPeliculasActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(btnMostrarPeliculas);
        btnMostrarPeliculas.setBounds(260, 270, 80, 30);

        descrAdmin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        descrAdmin.setForeground(new java.awt.Color(255, 255, 255));
        descrAdmin.setText("Perfil: Administrador");
        adminFrame.getContentPane().add(descrAdmin);
        descrAdmin.setBounds(750, 470, 120, 30);

        btnRegresarAdmin_main.setBackground(new java.awt.Color(153, 255, 0));
        btnRegresarAdmin_main.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarAdmin_main.setText("Regresar");
        btnRegresarAdmin_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarAdmin_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAdmin_mainActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(btnRegresarAdmin_main);
        btnRegresarAdmin_main.setBounds(20, 460, 100, 23);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        adminFrame.getContentPane().add(background1);
        background1.setBounds(0, 0, 890, 500);

        panelAño.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        panelAño.setOpaque(false);
        panelAño.setLayout(null);

        txtDirectorPelicula1.setBackground(new java.awt.Color(255, 255, 255));
        txtDirectorPelicula1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDirectorPelicula1.setForeground(new java.awt.Color(0, 0, 0));
        txtDirectorPelicula1.setBorder(null);
        txtDirectorPelicula1.setCaretColor(new java.awt.Color(0, 0, 0));
        panelAño.add(txtDirectorPelicula1);
        txtDirectorPelicula1.setBounds(10, 5, 340, 20);

        adminFrame.getContentPane().add(panelAño);
        panelAño.setBounds(100, 130, 360, 30);

        modificarFrame.setPreferredSize(new java.awt.Dimension(890, 535));
        modificarFrame.setSize(new java.awt.Dimension(890, 535));
        modificarFrame.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consultar Pelicula");
        modificarFrame.getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 40, 140, 30);

        panelCompras1.setBackground(new java.awt.Color(51, 51, 51));
        panelCompras1.setForeground(new java.awt.Color(51, 51, 51));
        panelCompras1.setLayout(null);

        txtConsultarCompras1.setBackground(new java.awt.Color(51, 51, 51));
        txtConsultarCompras1.setColumns(20);
        txtConsultarCompras1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtConsultarCompras1.setForeground(new java.awt.Color(255, 255, 255));
        txtConsultarCompras1.setRows(5);
        jScrollPane3.setViewportView(txtConsultarCompras1);

        panelCompras1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 320, 280);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Pelicula");
        panelCompras1.add(jLabel4);
        jLabel4.setBounds(10, 20, 80, 30);

        txtIdClienteConsultar1.setBackground(new java.awt.Color(51, 51, 51));
        txtIdClienteConsultar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdClienteConsultar1.setForeground(new java.awt.Color(255, 255, 255));
        panelCompras1.add(txtIdClienteConsultar1);
        txtIdClienteConsultar1.setBounds(100, 20, 220, 30);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 30, true));
        jPanel3.setLayout(null);

        btnBuscarCliente1.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarCliente1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCliente1.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarCliente1.setText("Buscar");
        btnBuscarCliente1.setBorder(null);
        btnBuscarCliente1.setBorderPainted(false);
        btnBuscarCliente1.setContentAreaFilled(false);
        btnBuscarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliente1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCliente1);
        btnBuscarCliente1.setBounds(10, 0, 110, 30);

        panelCompras1.add(jPanel3);
        jPanel3.setBounds(110, 70, 130, 30);

        modificarFrame.getContentPane().add(panelCompras1);
        panelCompras1.setBounds(510, 70, 340, 400);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 60, true));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modificar Pelicula");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 0, 230, 50);

        modificarFrame.getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 90, 270, 50);

        btnRegresarModificar_Admin.setBackground(new java.awt.Color(153, 255, 0));
        btnRegresarModificar_Admin.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarModificar_Admin.setText("Regresar");
        btnRegresarModificar_Admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarModificar_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarModificar_AdminActionPerformed(evt);
            }
        });
        modificarFrame.getContentPane().add(btnRegresarModificar_Admin);
        btnRegresarModificar_Admin.setBounds(20, 460, 100, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peliCenterLogoSmall.png"))); // NOI18N
        modificarFrame.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 60);

        titulo1.setFont(new java.awt.Font("Berlin Sans FB", 0, 40)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setText("CompraFilms");
        modificarFrame.getContentPane().add(titulo1);
        titulo1.setBounds(80, 20, 270, 50);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        modificarFrame.getContentPane().add(background2);
        background2.setBounds(0, 0, 890, 500);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CompraFilms");
        setPreferredSize(new java.awt.Dimension(890, 535));
        setResizable(false);
        setSize(new java.awt.Dimension(890, 535));
        getContentPane().setLayout(null);

        autores.setForeground(new java.awt.Color(255, 255, 255));
        autores.setText("Creado por: Jorge Silva, Samuel Tilano, Rafael Mejia");
        getContentPane().add(autores);
        autores.setBounds(10, 480, 300, 16);

        descripcion.setForeground(new java.awt.Color(255, 255, 255));
        descripcion.setText("ID administrador: admin");
        getContentPane().add(descripcion);
        descripcion.setBounds(730, 480, 150, 16);

        iconPelicenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPelicenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/peliCenterLogo.png"))); // NOI18N
        getContentPane().add(iconPelicenter);
        iconPelicenter.setBounds(150, 70, 110, 100);

        jPanel5.setBackground(new java.awt.Color(52, 121, 40));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 66, 60), 50, true));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        btnAcceder.setBackground(new java.awt.Color(153, 0, 0));
        btnAcceder.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 153));
        btnAcceder.setText("Iniciar");
        btnAcceder.setBorder(null);
        btnAcceder.setBorderPainted(false);
        btnAcceder.setContentAreaFilled(false);
        btnAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceder.setIconTextGap(2);
        btnAcceder.setMargin(new java.awt.Insets(0, 0, 0, 14));
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        jPanel5.add(btnAcceder);
        btnAcceder.setBounds(10, 4, 140, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(370, 270, 160, 40);

        id.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID:");
        getContentPane().add(id);
        id.setBounds(270, 190, 50, 40);

        titulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 80)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("CompraFilms");
        getContentPane().add(titulo);
        titulo.setBounds(250, 80, 440, 90);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        txtIdSesion.setBackground(new java.awt.Color(255, 255, 255));
        txtIdSesion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtIdSesion.setForeground(new java.awt.Color(0, 0, 0));
        txtIdSesion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdSesion.setToolTipText("Ingrese su ID");
        txtIdSesion.setBorder(null);
        txtIdSesion.setCaretColor(new java.awt.Color(0, 0, 0));
        txtIdSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIdSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtIdSesion.setOpaque(true);
        txtIdSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdSesionKeyPressed(evt);
            }
        });
        jPanel4.add(txtIdSesion);
        txtIdSesion.setBounds(10, 8, 250, 20);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(320, 190, 270, 35);

        background.setForeground(new java.awt.Color(255, 255, 153));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 890, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        String idusuario = txtIdSesion.getText();
        if (idusuario.equals(idAdministrador)) {
            this.dispose();
            adminFrame.setLocationRelativeTo(null);
            adminFrame.setVisible(true);
        } else {
            archivoCliente.existeId(Integer.parseInt(idusuario));
        }

    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnRegresarAdmin_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAdmin_mainActionPerformed
        adminFrame.setVisible(false);
        mostrarMainPeliculas();
    }//GEN-LAST:event_btnRegresarAdmin_mainActionPerformed

    private void btnTodasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodasComprasActionPerformed
    StringBuilder sb = new StringBuilder();
        for (Compra compra : compras){
            sb.append("ID:"+compra.getIdecompra()+"| IDCliente:"+compra.getIdecliente()+"| IDPelicula:"+compra.getIdepelicula()+"| Fecha:"+compra.getFechacompra()+
                    "\n---------------------------------------------------").append("\n");
    }
        txtConsultarCompras.setText(sb.toString());
    }//GEN-LAST:event_btnTodasComprasActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        StringBuilder sb = new StringBuilder();
        int clienteBuscar = Integer.parseInt(txtIdClienteConsultar.getText());
        txtConsultarCompras.setForeground(Color.white);
        comprasCliente = archivoCompra.buscarCompraCliente(clienteBuscar);
        for (Compra compra : comprasCliente){
            sb.append("IDCompra:"+compra.getIdecompra()+"| IDCliente:"+compra.getIdecliente()+"| IDPelicula:"+compra.getIdepelicula()+"| Fecha:"+compra.getFechacompra()+
                    "\n---------------------------------------------------").append("\n");
        }
        txtConsultarCompras.setText(sb.toString());
        if(comprasCliente.isEmpty()){
            txtConsultarCompras.setText("EL CLIENTE CON EL ID: "+clienteBuscar+"  NO HA REALIZADO COMPRAS");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnRegresarModificar_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarModificar_AdminActionPerformed
        modificarFrame.setVisible(false);
        adminFrame.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarModificar_AdminActionPerformed

    private void btnBuscarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente1ActionPerformed

    private void txtIdSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSesionKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            this.btnAcceder.doClick();
        }
    }//GEN-LAST:event_txtIdSesionKeyPressed

    private void btnMostrarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPeliculasActionPerformed
        txtPeliculasAdmin.setForeground(Color.white);
        StringBuilder sb = new StringBuilder();

        try ( BufferedReader br = new BufferedReader(new FileReader("src/archivos/peliculas.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                // Separar los campos por comas
                sb.append(linea+"\n"
                    + "---------------------------------------------------------------------------------------------------").append("\n");
            }
            txtPeliculasAdmin.setText(sb.toString());

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnMostrarPeliculasActionPerformed

    private void btnEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliculaActionPerformed
        int idpeliculaEliminar = Integer.parseInt(txtIdPelicula.getText());
        if (archivoPelicula.existeId(idpeliculaEliminar)) {
            archivoPelicula.eliminarPelicula(idpeliculaEliminar);
            txtPeliculasAdmin.setForeground(Color.green);
            txtPeliculasAdmin.setText("¡PELICULA ELIMINADA EXITOSAMENTE! ");
            txtIdPelicula.setText("");
            txtTituloPelicula.setText("");
            txtDirectorPelicula.setText("");
            txtAñoPelicula.setText("");
            txtGeneroPelicula.setText("");
            txtPrecioPelicula.setText("");
        } else {
            txtPeliculasAdmin.setForeground(Color.red);
            txtPeliculasAdmin.setText("¡EL ID INGRESADO NO EXISTE!");
        }
    }//GEN-LAST:event_btnEliminarPeliculaActionPerformed

    private void btnModificarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPeliculaActionPerformed
        adminFrame.setVisible(false);
        modificarFrame.setLocationRelativeTo(null);
        modificarFrame.setVisible(true);
    }//GEN-LAST:event_btnModificarPeliculaActionPerformed

    private void btnRegistrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPeliculaActionPerformed
        int idpelicula = Integer.parseInt(txtIdPelicula.getText());
        String tituloPelicula = txtTituloPelicula.getText();
        String directorPelicula = txtDirectorPelicula.getText();
        int añoPelicula = Integer.parseInt(txtAñoPelicula.getText());
        String generoPelicula = txtGeneroPelicula.getText();
        Double precioPelicula = Double.parseDouble(txtPrecioPelicula.getText());
        if (archivoPelicula.existeId(idpelicula)) {
            txtPeliculasAdmin.setForeground(Color.red);
            txtPeliculasAdmin.setText("¡EL ID INGRESADO YA EXISTE\nIntenta con otro id.");
        } else {
            txtPeliculasAdmin.setText("¡PELICULA REGISTRADA EXITOSAMENTE!");
            archivoPelicula.registrarPelicula(idpelicula, tituloPelicula, directorPelicula, añoPelicula, generoPelicula, precioPelicula);

            txtIdPelicula.setText("");
            txtTituloPelicula.setText("");
            txtDirectorPelicula.setText("");
            txtAñoPelicula.setText("");
            txtGeneroPelicula.setText("");
            txtPrecioPelicula.setText("");
        }
    }//GEN-LAST:event_btnRegistrarPeliculaActionPerformed

    private void txtTituloPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloPeliculaActionPerformed

    public static void mostrarMainPeliculas() {
        // Crea una nueva instancia de GestionPeliculas y la muestra
        GestionPeliculas gestionPeliculas = new GestionPeliculas();
        gestionPeliculas.setVisible(true);
    }
    
 
        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame adminFrame;
    private javax.swing.JLabel autores;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarCliente1;
    private javax.swing.JButton btnEliminarPelicula;
    private javax.swing.JButton btnModificarPelicula;
    private javax.swing.JButton btnMostrarPeliculas;
    private javax.swing.JButton btnRegistrarPelicula;
    private javax.swing.JButton btnRegresarAdmin_main;
    private javax.swing.JButton btnRegresarModificar_Admin;
    private javax.swing.JButton btnTodasCompras;
    private javax.swing.JFrame clienteNoRegistrado;
    private javax.swing.JFrame clienteRegistrado;
    private javax.swing.JLabel descrAdmin;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel iconPelicenter;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFrame modificarFrame;
    private javax.swing.JPanel panelAño;
    private javax.swing.JPanel panelCompras;
    private javax.swing.JPanel panelCompras1;
    private javax.swing.JPanel panelDirector;
    private javax.swing.JPanel panelID;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel tituloRegistrarPelicula;
    private javax.swing.JLabel tituloRegistrarPelicula1;
    private javax.swing.JTextField txtAñoPelicula;
    private javax.swing.JTextArea txtConsultarCompras;
    private javax.swing.JTextArea txtConsultarCompras1;
    private javax.swing.JTextField txtDirectorPelicula;
    private javax.swing.JTextField txtDirectorPelicula1;
    private javax.swing.JTextField txtGeneroPelicula;
    private javax.swing.JTextField txtIdClienteConsultar;
    private javax.swing.JTextField txtIdClienteConsultar1;
    private javax.swing.JTextField txtIdPelicula;
    private javax.swing.JTextField txtIdSesion;
    private javax.swing.JTextArea txtPeliculasAdmin;
    private javax.swing.JTextField txtPrecioPelicula;
    private javax.swing.JTextField txtTituloPelicula;
    // End of variables declaration//GEN-END:variables


}
